In [ ]:
## Example from HKMA

# https://apidocs.hkma.gov.hk/documentation/market-data-and-statistics/monthly-statistical-bulletin/financial/economic-statistics/

# Example From HKMA

In [2]:
import urllib.request

url = 'https://api.hkma.gov.hk/public/market-data-and-statistics/monthly-statistical-bulletin/financial/economic-statistics'

with urllib.request.urlopen (url) as req:
    print (req.read())

b'{"header":{"success":true,"err_code":"0000","err_msg":"No error found"},"result":{"datasize":20,"records":[{"end_of_month":"2019-09","nominal_gdp":null,"real_gdp":null,"gov_consol_bal":null,"composite_cpi":null,"unemploy_rate":null,"curr_acc_bal":null,"fc_reserve":null},{"end_of_month":"2019-08","nominal_gdp":null,"real_gdp":null,"gov_consol_bal":-14837.3,"composite_cpi":110.888,"unemploy_rate":2.9,"curr_acc_bal":null,"fc_reserve":432.843},{"end_of_month":"2019-07","nominal_gdp":null,"real_gdp":null,"gov_consol_bal":-12330.4,"composite_cpi":110.686,"unemploy_rate":2.9,"curr_acc_bal":null,"fc_reserve":448.441},{"end_of_month":"2019-06","nominal_gdp":698700,"real_gdp":657429,"gov_consol_bal":-10492.4,"composite_cpi":110.224,"unemploy_rate":2.8,"curr_acc_bal":37770,"fc_reserve":445.689},{"end_of_month":"2019-05","nominal_gdp":null,"real_gdp":null,"gov_consol_bal":-9952.8,"composite_cpi":109.482,"unemploy_rate":2.8,"curr_acc_bal":null,"fc_reserve":437.788},{"end_of_month":"2019-04","nominal_gdp":null,"real_gdp":null,"gov_consol_bal":5627.8,"composite_cpi":109.566,"unemploy_rate":2.8,"curr_acc_bal":null,"fc_reserve":436.411},{"end_of_month":"2019-03","nominal_gdp":712514,"real_gdp":674829,"gov_consol_bal":-31853.8,"composite_cpi":108.788,"unemploy_rate":2.8,"curr_acc_bal":35107,"fc_reserve":437.983},{"end_of_month":"2019-02","nominal_gdp":null,"real_gdp":null,"gov_consol_bal":-8287.3,"composite_cpi":109.125,"unemploy_rate":2.8,"curr_acc_bal":null,"fc_reserve":434.439},{"end_of_month":"2019-01","nominal_gdp":null,"real_gdp":null,"gov_consol_bal":49086.1,"composite_cpi":108.128,"unemploy_rate":2.8,"curr_acc_bal":null,"fc_reserve":432.107},{"end_of_month":"2018-12","nominal_gdp":754904,"real_gdp":721686,"gov_consol_bal":86844.7,"composite_cpi":108.281,"unemploy_rate":2.8,"curr_acc_bal":40393,"fc_reserve":424.62},{"end_of_month":"2018-11","nominal_gdp":null,"real_gdp":null,"gov_consol_bal":18173.4,"composite_cpi":107.901,"unemploy_rate":2.8,"curr_acc_bal":null,"fc_reserve":423.173},{"end_of_month":"2018-10","nominal_gdp":null,"real_gdp":null,"gov_consol_bal":29317.7,"composite_cpi":107.661,"unemploy_rate":2.8,"curr_acc_bal":null,"fc_reserve":423.167},{"end_of_month":"2018-09","nominal_gdp":726352,"real_gdp":696011,"gov_consol_bal":-9304.1,"composite_cpi":107.419,"unemploy_rate":2.8,"curr_acc_bal":47715,"fc_reserve":426.403},{"end_of_month":"2018-08","nominal_gdp":null,"real_gdp":null,"gov_consol_bal":-23601.3,"composite_cpi":107.185,"unemploy_rate":2.8,"curr_acc_bal":null,"fc_reserve":424.804},{"end_of_month":"2018-07","nominal_gdp":null,"real_gdp":null,"gov_consol_bal":-18013.9,"composite_cpi":107.176,"unemploy_rate":2.8,"curr_acc_bal":null,"fc_reserve":431.906},{"end_of_month":"2018-00","nominal_gdp":2842883,"real_gdp":2742787,"gov_consol_bal":67948.817,"composite_cpi":107.034166666667,"unemploy_rate":2.8,"curr_acc_bal":121937,"fc_reserve":424.62},{"end_of_month":"2017-00","nominal_gdp":2662836,"real_gdp":2662836,"gov_consol_bal":148973.304,"composite_cpi":104.521333333333,"unemploy_rate":3.1,"curr_acc_bal":123900,"fc_reserve":431.442},{"end_of_month":"2016-00","nominal_gdp":2490617,"real_gdp":2564130,"gov_consol_bal":111072.707,"composite_cpi":103.00025,"unemploy_rate":3.4,"curr_acc_bal":98664,"fc_reserve":386.294},{"end_of_month":"2015-00","nominal_gdp":2398280,"real_gdp":2509513,"gov_consol_bal":14373.517,"composite_cpi":100.574,"unemploy_rate":3.3,"curr_acc_bal":79553,"fc_reserve":358.773},{"end_of_month":"2014-00","nominal_gdp":2260005,"real_gdp":2450989,"gov_consol_bal":72797.466,"composite_cpi":97.7,"unemploy_rate":3.3,"curr_acc_bal":31453,"fc_reserve":328.516}]}}'

# Code to download Economic Data

In [3]:
import requests 

url = 'https://api.hkma.gov.hk/public/market-data-and-statistics/monthly-statistical-bulletin/financial/economic-statistics'

r = requests.get(url)

json_data = r.json()

In [22]:
# results is the key, records is also the keys, now we can get the real-time economic data via json format
data = json_data['result']['records']

headers = list(data[0].keys())

dataList = []

for i in data:
    lista = list(i.values())
    dataList.append(lista)
    
import pandas as pd

df = pd.DataFrame(dataList, columns = headers)

df

,end_of_month,nominal_gdp,real_gdp,gov_consol_bal,composite_cpi,unemploy_rate,curr_acc_bal,fc_reserve
0,2019-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-08,NaN,NaN,-14837.300,110.888000,2.9,NaN,432.843
2,2019-07,NaN,NaN,-12330.400,110.686000,2.9,NaN,448.441
3,2019-06,698700.0,657429.0,-10492.400,110.224000,2.8,37770.0,445.689
4,2019-05,NaN,NaN,-9952.800,109.482000,2.8,NaN,437.788
5,2019-04,NaN,NaN,5627.800,109.566000,2.8,NaN,436.411
6,2019-03,712514.0,674829.0,-31853.800,108.788000,2.8,35107.0,437.983
7,2019-02,NaN,NaN,-8287.300,109.125000,2.8,NaN,434.439
8,2019-01,NaN,NaN,49086.100,108.128000,2.8,NaN,432.107
9,2018-12,754904.0,721686.0,86844.700,108.281000,2.8,40393.0,424.620
10,2018-11,NaN,NaN,18173.400,107.901000,2.8,NaN,423.173
11,2018-10,NaN,NaN,29317.700,107.661000,2.8,NaN,423.167
12,2018-09,726352.0,696011.0,-9304.100,107.419000,2.8,47715.0,426.403
13,2018-08,NaN,NaN,-23601.300,107.185000,2.8,NaN,424.804
14,2018-07,NaN,NaN,-18013.900,107.176000,2.8,NaN,431.906
15,2018-00,2842883.0,2742787.0,67948.817,107.034167,2.8,121937.0,424.620
16,2017-00,2662836.0,2662836.0,148973.304,104.521333,3.1,123900.0,431.442
17,2016-00,2490617.0,2564130.0,111072.707,103.000250,3.4,98664.0,386.294
18,2015-00,2398280.0,2509513.0,14373.517,100.574000,3.3,79553.0,358.773
19,2014-00,2260005.0,2450989.0,72797.466,97.700000,3.3,31453.0,328.516

# Code to download Capital Market Data

In [23]:
import pandas as pd
import requests


url_cm = "https://api.hkma.gov.hk/public/market-data-and-statistics/monthly-statistical-bulletin/financial/capital-market-statistics"

r2 = requests.get(url_cm)

json_data_2 = r2.json()

# results is the key, records is also the keys, now we can get the real-time economic data via json format
data_cm = json_data_2['result']['records']

headers = list(data_cm[0].keys())

dataList = []

for i in data_cm:
    lista = list(i.values())
    dataList.append(lista)
    
import pandas as pd

df = pd.DataFrame(dataList, columns = headers)

df

,end_of_month,hkd_drmkt_outstand_efbn,hkd_drmkt_outstand_odrinst,hkd_drmkt_outstand_total,hkd_drmkt_new_non_efbn,eq_mkt_hs_index,eq_mkt_ttl_stock_cap,eq_mkt_fund_raised
0,2019-09,1076775,NaN,NaN,NaN,26092.27,3.064269e+07,4.428457e+04
1,2019-08,1075226,NaN,NaN,NaN,25724.73,2.999934e+07,1.455204e+04
2,2019-07,1073597,NaN,NaN,NaN,27777.75,3.208570e+07,2.146480e+04
3,2019-06,1071332,791446.038553,1.862778e+06,75859.900000,28542.62,3.272665e+07,4.357164e+04
4,2019-05,1069849,NaN,NaN,NaN,26901.09,3.103949e+07,1.477180e+04
5,2019-04,1067917,NaN,NaN,NaN,29699.11,3.434439e+07,4.576340e+04
6,2019-03,1066470,798703.828553,1.865174e+06,108434.500000,29051.36,3.381471e+07,2.222026e+04
7,2019-02,1065444,NaN,NaN,NaN,28633.18,3.304457e+07,1.074859e+04
8,2019-01,1064564,NaN,NaN,NaN,27942.47,3.204097e+07,1.215534e+04
9,2018-12,1062715,781796.038553,1.844511e+06,54324.800000,25845.70,2.990942e+07,3.980295e+04
10,2018-11,1061277,NaN,NaN,NaN,26506.75,3.078474e+07,2.829936e+04
11,2018-10,1060014,NaN,NaN,NaN,24979.69,2.878494e+07,2.859082e+04
12,2018-09,1057989,761016.848553,1.819006e+06,61972.000000,27788.52,3.216657e+07,7.641607e+04
13,2018-08,1056769,NaN,NaN,NaN,27888.55,3.220832e+07,9.464573e+04
14,2018-07,1055328,NaN,NaN,NaN,28583.01,3.295954e+07,8.368808e+04
15,2018-00,1062715,781796.038553,1.844511e+06,322163.860000,25845.70,2.990942e+07,5.441348e+05
16,2017-00,1048479,753609.668553,1.802089e+06,334871.000000,29919.15,3.399884e+07,5.813856e+05
17,2016-00,963098,767468.300553,1.730566e+06,362942.264000,22000.56,2.476131e+07,4.900540e+05
18,2015-00,828421,688616.243353,1.517037e+06,251810.592000,21914.40,2.468373e+07,1.115643e+06
19,2014-00,752630,657181.643347,1.409812e+06,252721.748794,23605.04,2.507183e+07,9.427166e+05